name: pull-request-merged

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
      - name : log
        run: echo ${{ toJson(steps.check.outputs) }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm install
      - run: npm ci
      - name: if version has been updated, publish to npm
        if: steps.check.outputs.updated == 'true'
        run: npm publish
        
      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
      - name: post to twitter
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
            twitter_status: "Akroma React Native ( npm package )\n\nPR MERGED:\n${{ github.event.head_commit.message }} 🥳 \n ${{ github.event.head_commit.url }}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 