name: pull-request-merged

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: post-notice-to-twitter
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
            twitter_status: "Akroma React Native ( npm package )\n\nPR MERGED:\n${{ github.event.head_commit.message }} 🥳 \n ${{ github.event.head_commit.url }}"
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} 